datasets: "phen,soma"

# pathes
path_loci: "config/locus_window_test.txt"
path_vcf: "/scratch/dariush.ghasemi/projects/haploAnalysis/data/chr22_no_indels_freq.vcf.gz"
path_rep: "/scratch/dariush.ghasemi/projects/haploAnalysis/workflow"
phenotype_files: "data/my_phenos.tsv,  data/my_soma.tsv"
covariates_file: "data/my_covars.tsv"

thresholds:
    min_freq: 0.01
    max_haps: 4e6
    min_pp: 1e-5


#phenotype_files: "data/chris_q-norm.csv, data/chris_meta.csv,  data/chris_prot.csv"
#covariates_file: "data/CHRIS13K.GT.evecs"